# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossing_brownbridge <- function(x0, xt, t, ncross, epsilon, up = TRUE, counditional = TRUE) {
    .Call('BMIthreshCount_crossing_brownbridge', PACKAGE = 'BMIthreshCount', x0, xt, t, ncross, epsilon, up, counditional)
}

brown_crossing_sample <- function(x0, xt, t, epsilon, up = TRUE, nsize = 1L) {
    .Call('BMIthreshCount_brown_crossing_sample', PACKAGE = 'BMIthreshCount', x0, xt, t, epsilon, up, nsize)
}

fills_in_cpp <- function(edge, edgelength, Nnode, data, epsilon, thed = 0, cut = 0L, less = FALSE) {
    .Call('BMIthreshCount_fills_in_cpp', PACKAGE = 'BMIthreshCount', edge, edgelength, Nnode, data, epsilon, thed, cut, less)
}

fills_in_mat <- function(edge, edgelength, Nnode, data, epsilon, thed = 0, cut = 0L, less = FALSE) {
    .Call('BMIthreshCount_fills_in_mat', PACKAGE = 'BMIthreshCount', edge, edgelength, Nnode, data, epsilon, thed, cut, less)
}

brown_tree_prior_node_cpp <- function(edge, edgelength, Nnode, rootprior, nsize) {
    .Call('BMIthreshCount_brown_tree_prior_node_cpp', PACKAGE = 'BMIthreshCount', edge, edgelength, Nnode, rootprior, nsize)
}

trnorm0 <- function(mu, sigma, d, nsize = 1L) {
    .Call('BMIthreshCount_trnorm0', PACKAGE = 'BMIthreshCount', mu, sigma, d, nsize)
}

getneighbor_cpp <- function(edge, edgelength, Nnode) {
    .Call('BMIthreshCount_getneighbor_cpp', PACKAGE = 'BMIthreshCount', edge, edgelength, Nnode)
}

posterior_update <- function(edge, edgelength, Nnode, d, thed, rootprior, ngen, burnin, thin = 1L) {
    .Call('BMIthreshCount_posterior_update', PACKAGE = 'BMIthreshCount', edge, edgelength, Nnode, d, thed, rootprior, ngen, burnin, thin)
}

twoStateRateMatrix <- function(lambda_01, lambda_10) {
    .Call('BMIthreshCount_twoStateRateMatrix', PACKAGE = 'BMIthreshCount', lambda_01, lambda_10)
}

TwoStatePhyloLikelihood1 <- function(treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist) {
    .Call('BMIthreshCount_TwoStatePhyloLikelihood1', PACKAGE = 'BMIthreshCount', treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist)
}

TwoStatePhyloLikelihood2 <- function(treeEdges, tipStates, branchLengths, lambda_01, lambda_10, armaRootDist) {
    .Call('BMIthreshCount_TwoStatePhyloLikelihood2', PACKAGE = 'BMIthreshCount', treeEdges, tipStates, branchLengths, lambda_01, lambda_10, armaRootDist)
}

